#druid
spring:
  profiles:
    active: dev
#  druid:
#    url: jdbc:mysql://localhost:8080/tima8090?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    maxActive: 30 #最大链接数
#    maxWait: 10000 #获得链接的最大等待时间
#  jpa:
#    show-sql: true  #显示sql语句
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss  #日期格式化标准
#    #default-property-inclusion: non_null  #返回json时 忽略null
server:
  port: 8888


